export const evalu = {
  1: [
    { label: "1.", value: "p1_1" },
    { label: "2.", value: "p1_2" },
    { label: "3.", value: "p1_3" },
    { label: "4.", value: "p1_4" },
    { label: "5.", value: "p1_5" },
    { label: "6.", value: "p1_6" },
    { label: "จุดแข็ง", value: "strength" },
    { label: "จุดที่ต้องปรับปรุง", value: "improvement" },
  ],
  2: [
    { label: "1.", value: "p1_1" },
    { label: "2.", value: "p1_2" },
    { label: "3.", value: "p1_3" },
    { label: "4.", value: "p1_4" },
    { label: "5.", value: "p1_5" },
    { label: "6.", value: "p1_6" },
    { label: "จุดแข็ง", value: "strength" },
    { label: "จุดที่ต้องปรับปรุง", value: "improvement" },
  ],
  3: [
    { label: "สถานที่ประเมิน", value: "location" },
    { label: "สถานที่อื่นๆ", value: "locationOther" },
    { label: "บุคลากรที่สื่อสารด้วย", value: "communicator" },
    { label: "บุคลากรอื่นๆ", value: "communicatorOther" },
    { label: "ความยาก/ง่าย", value: "level" },
    { label: "1.", value: "p1" },
    { label: "2.", value: "p2" },
    { label: "3.", value: "p3" },
    { label: "จุดแข็ง", value: "strength" },
    { label: "จุดที่ต้องปรับปรุง", value: "improvement" },
  ],
};
