export const supervi = {
  1: [
    { label: "ชื่อแหล่งฝึก", value: "siteName" },
    { label: "จังหวัด", value: "province" },
    { label: "ชื่อ-สกุล ผู้ติดต่อ/ผู้รับผิดชอบ", value: "fullname" },
    { label: "E-mail", value: "email" },
    { label: "โทรศัพท์", value: "phone" },
    { label: "ที่อยู่", value: "address" },
    { label: "ถนน", value: "street" },
    { label: "ตำบล/แขวง", value: "subdistrict" },
    { label: "อำเภอ/เขต", value: "district" },
    { label: "เภสัชกรผู้รับผิดชอบ", value: "pharmacist" },
    { label: "มหาวิทยาลัยที่รับฝึก - จุฬา", value: "uniSelected.จุฬา" },
    { label: "มหาวิทยาลัยที่รับฝึก - มหิดล", value: "uniSelected.มหิดล" },
    {
      label: "มหาวิทยาลัยที่รับฝึก - เชียงใหม่",
      value: "uniSelected.เชียงใหม่",
    },
    { label: "มหาวิทยาลัยที่รับฝึก - สงขลา", value: "uniSelected.สงขลา" },
    { label: "มหาวิทยาลัยที่รับฝึก - ขอนแก่น", value: "uniSelected.ขอนแก่น" },
    { label: "มหาวิทยาลัยที่รับฝึก - ศิลปากร", value: "uniSelected.ศิลปากร" },
    { label: "มหาวิทยาลัยที่รับฝึก - นเรศวร", value: "uniSelected.นเรศวร" },
    {
      label: "มหาวิทยาลัยที่รับฝึก - อุบลราชธานี",
      value: "uniSelected.อุบลราชธานี",
    },
    {
      label: "มหาวิทยาลัยที่รับฝึก - ศรีนครินทรวิโรฒ",
      value: "uniSelected.ศรีนครินทรวิโรฒ",
    },
    {
      label: "มหาวิทยาลัยที่รับฝึก - มหาสารคาม",
      value: "uniSelected.มหาสารคาม",
    },
    { label: "มหาวิทยาลัยที่รับฝึก - รังสิต", value: "uniSelected.รังสิต" },
    {
      label: "มหาวิทยาลัยที่รับฝึก - หัวเฉียวฯ",
      value: "uniSelected.หัวเฉียวฯ",
    },
    { label: "มหาวิทยาลัยที่รับฝึก - สยาม", value: "uniSelected.สยาม" },
    { label: "มหาวิทยาลัยที่รับฝึก - พายัพ", value: "uniSelected.พายัพ" },
    {
      label: "มหาวิทยาลัยที่รับฝึก - วลัยลักษณ์",
      value: "uniSelected.วลัยลักษณ์",
    },
    { label: "มหาวิทยาลัยที่รับฝึก - พะเยา", value: "uniSelected.พะเยา" },
    {
      label: "มหาวิทยาลัยที่รับฝึก - อีสเทิร์น",
      value: "uniSelected.อีสเทิร์น",
    },
    { label: "มหาวิทยาลัยอื่นๆ (ระบุ)", value: "uniOther" },
    { label: "ที่พัก", value: "accommodation" },
    { label: "ความปลอดภัยของที่พักและการเดินทาง", value: "safety_travel" },
    { label: "หมายเหตุความปลอดภัยที่พัก", value: "safety_travel_note" },
    { label: "ความปลอดภัยของสิ่งแวดล้อมโดยรอบ", value: "safety_env" },
    { label: "หมายเหตุความปลอดภัยสิ่งแวดล้อม", value: "safety_env_note" },
    { label: "ยา - ฝึกรวม", value: "product.1_1" },
    { label: "ยา - การผลิต", value: "product.1_2" },
    { label: "ยา - การควบคุมคุณภาพ", value: "product.1_3" },
    { label: "ยา - การวิจัยและพัฒนา", value: "product.1_4" },
    { label: "ยา - การขึ้นทะเบียน", value: "product.1_5" },
    { label: "ยา - การคุ้มครองผู้บริโภค", value: "product.1_6" },
    { label: "ยา - อื่นๆ", value: "product.1_7" },
    { label: "ยา - ไม่มีการฝึก", value: "product.1_8" },
    { label: "ชีววัตถุ - ฝึกรวม", value: "product.2_1" },
    { label: "ชีววัตถุ - การผลิต", value: "product.2_2" },
    { label: "ชีววัตถุ - การควบคุมคุณภาพ", value: "product.2_3" },
    { label: "ชีววัตถุ - การวิจัยและพัฒนา", value: "product.2_4" },
    { label: "ชีววัตถุ - การขึ้นทะเบียน", value: "product.2_5" },
    { label: "ชีววัตถุ - การคุ้มครองผู้บริโภค", value: "product.2_6" },
    { label: "ชีววัตถุ - อื่นๆ", value: "product.2_7" },
    { label: "ชีววัตถุ - ไม่มีการฝึก", value: "product.2_8" },
    { label: "เครื่องสำอาง - ฝึกรวม", value: "product.3_1" },
    { label: "เครื่องสำอาง - การผลิต", value: "product.3_2" },
    { label: "เครื่องสำอาง - การควบคุมคุณภาพ", value: "product.3_3" },
    { label: "เครื่องสำอาง - การวิจัยและพัฒนา", value: "product.3_4" },
    { label: "เครื่องสำอาง - การขึ้นทะเบียน", value: "product.3_5" },
    { label: "เครื่องสำอาง - การคุ้มครองผู้บริโภค", value: "product.3_6" },
    { label: "เครื่องสำอาง - อื่นๆ", value: "product.3_7" },
    { label: "เครื่องสำอาง - ไม่มีการฝึก", value: "product.3_8" },
    { label: "สมุนไพร - ฝึกรวม", value: "product.4_1" },
    { label: "สมุนไพร - การผลิต", value: "product.4_2" },
    { label: "สมุนไพร - การควบคุมคุณภาพ", value: "product.4_3" },
    { label: "สมุนไพร - การวิจัยและพัฒนา", value: "product.4_4" },
    { label: "สมุนไพร - การขึ้นทะเบียน", value: "product.4_5" },
    { label: "สมุนไพร - การคุ้มครองผู้บริโภค", value: "product.4_6" },
    { label: "สมุนไพร - อื่นๆ", value: "product.4_7" },
    { label: "สมุนไพร - ไม่มีการฝึก", value: "product.4_8" },
    { label: "อาหารและผลิตภัณฑ์เสริมอาหาร - ฝึกรวม", value: "product.5_1" },
    { label: "อาหารและผลิตภัณฑ์เสริมอาหาร - การผลิต", value: "product.5_2" },
    {
      label: "อาหารและผลิตภัณฑ์เสริมอาหาร - การควบคุมคุณภาพ",
      value: "product.5_3",
    },
    {
      label: "อาหารและผลิตภัณฑ์เสริมอาหาร - การวิจัยและพัฒนา",
      value: "product.5_4",
    },
    {
      label: "อาหารและผลิตภัณฑ์เสริมอาหาร - การขึ้นทะเบียน",
      value: "product.5_5",
    },
    {
      label: "อาหารและผลิตภัณฑ์เสริมอาหาร - การคุ้มครองผู้บริโภค",
      value: "product.5_6",
    },
    { label: "อาหารและผลิตภัณฑ์เสริมอาหาร - อื่นๆ", value: "product.5_7" },
    {
      label: "อาหารและผลิตภัณฑ์เสริมอาหาร - ไม่มีการฝึก",
      value: "product.5_8",
    },
    { label: "คอมพิวเตอร์/อุปกรณ์เกี่ยวข้อง", value: "support_has" },
    { label: "จำนวนอุปกรณ์", value: "support_count" },
    { label: "ชื่ออุปกรณ์", value: "support_device" },
    { label: "รายละเอียดสิ่งสนับสนุน", value: "support_detail" },
    {
      label: "ตำราต่างประเทศ - Drug Information Handbook",
      value: "ref_foreign_drugHB",
    },
    {
      label: "ตำราต่างประเทศ - Pharmacotherapy",
      value: "ref_foreign_pharmacotherapy",
    },
    { label: "ตำราต่างประเทศ - อื่นๆ", value: "ref_foreign_other" },
    { label: "ตำราไทย/e-book/ฐานข้อมูล", value: "ref_thai" },
    { label: "ปัญหาข้อเสนอแนะเกี่ยวกับงาน/กิจกรรม", value: "issues" },
    {
      label: "ความต้องการการสนับสนุนจากคณะเภสัชศาสตร์",
      value: "needsFromFaculty",
    },
    { label: "เป็นแหล่งฝึกที่เหมาะสม", value: "siteEvaluation_isSuitable" },
    { label: "ข้อเสนอแนะอื่นๆ", value: "siteEvaluation_other" },
    { label: "หมายเหตุการประเมิน", value: "siteEvaluation_note" },
  ],
  2: [
    { label: "ชื่อแหล่งฝึก", value: "siteName" },
    { label: "ได้รับชี้แจงการฝึกปฏิบัติงาน", value: "informedBrief" },
    { label: "วันที่นิเทศ", value: "visitDate" },
    { label: "ครั้งที่", value: "visitRound" },
    { label: "ชื่อ-สกุลนักศึกษา คนที่ 1", value: "students.0" },
    { label: "ชื่อ-สกุลนักศึกษา คนที่ 2", value: "students.1" },
    { label: "ชื่อ-สกุลนักศึกษา คนที่ 3", value: "students.2" },
    { label: "ชื่อ-สกุลนักศึกษา คนที่ 4", value: "students.3" },
    { label: "สรุปผลจากการนิเทศ", value: "summary" },
    { label: "การรับนักศึกษาฝึกงาน", value: "acceptIntern" },
    { label: "มีนักศึกษาจากสถาบันอื่นร่วมฝึก", value: "withDormFromUni" },
    { label: "รายละเอียดสถาบันอื่น", value: "withDormFromUni_desc" },
    { label: "ไม่มีนักศึกษาจากสถาบันอื่น", value: "withoutDormFromUni" },
    {
      label: "ผลการติดตาม/นิเทศ - ข้อมูลแหล่งฝึก",
      value: "supervisionResult_section1",
    },
    { label: "ที่พักของโรงพยาบาล", value: "housing_opts.hospitalDorm" },
    { label: "ที่พักเอกชนที่แหล่งฝึกแนะนำ", value: "housing_opts.privateDorm" },
    { label: "บ้านพัก/บ้านญาติ", value: "housing_opts.house" },
    { label: "ที่พักอื่นๆ", value: "housing_opts.others" },
    { label: "รายละเอียดการเดินทาง/ความปลอดภัย", value: "housing_note" },
    {
      label: "ผลการติดตาม/นิเทศ - ที่พัก",
      value: "supervisionResult_section2",
    },
    {
      label: "แหล่งฝึกได้ให้รายชื่อการประสานงาน",
      value: "coord.gotContactPerson",
    },
    { label: "ต้องการข้อมูลเพิ่มเติม", value: "coord.needMoreInfo" },
    { label: "ติดต่อผ่านมือถือ", value: "coord.useMobile" },
    { label: "ติดต่อผ่านโทรศัพท์", value: "coord.usePhone" },
    { label: "ติดต่อผ่าน Email/Social", value: "coord.useEmailSocial" },
    { label: "รายละเอียดช่องทางติดต่อ", value: "coord.contactDetailProper" },
    { label: "หมายเหตุช่องทางติดต่อ", value: "coord.contactDetail_note" },
    {
      label: "ผลการติดตาม/นิเทศ - การประสานงาน",
      value: "supervisionResult_section3",
    },
    { label: "ความพร้อมแหล่งฝึก", value: "readiness_site.workloadFit" },
    {
      label: "หมายเหตุความพร้อมแหล่งฝึก",
      value: "readiness_site.workload_note",
    },
    { label: "บุคลิกภาพของนักศึกษา", value: "readiness_student.personality" },
    { label: "จริยธรรมของนักศึกษา", value: "readiness_student.ethics" },
    { label: "ความรู้ทางวิชาการ", value: "readiness_student.academic" },
    { label: "ความรับผิดชอบ", value: "readiness_student.responsibility" },
    { label: "การทำงานเป็นทีม", value: "readiness_student.teamwork" },
    { label: "วินัยในตนเอง", value: "readiness_student.selfDiscipline" },
    { label: "ความพร้อมนักศึกษา - อื่นๆ", value: "readiness_student.other" },
    {
      label: "ผลการติดตาม/นิเทศ - ความพร้อม",
      value: "supervisionResult_section4",
    },
    { label: "ต้องการสนับสนุน - หนังสือ/ตำรา", value: "needSupport.books" },
    {
      label: "ต้องการสนับสนุน - การประชุมวิชาการ",
      value: "needSupport.conferences",
    },
    {
      label: "ต้องการสนับสนุน - การอบรม/ดูงาน",
      value: "needSupport.trainingStudyVisit",
    },
    { label: "ต้องการสนับสนุน - อื่นๆ", value: "needSupport.other" },
    {
      label: "ผลการติดตาม/นิเทศ - การสนับสนุน",
      value: "supervisionResult_section5",
    },
    { label: "ไม่พบปัญหา/อุปสรรค", value: "issues.none" },
    { label: "พบปัญหา/อุปสรรค", value: "issues.found" },
    { label: "รายละเอียดปัญหา", value: "issues.found_note" },
    {
      label: "ผลการติดตาม/นิเทศ - ปัญหา/อุปสรรค",
      value: "supervisionResult_section6",
    },
    { label: "ประเด็นอื่นๆ", value: "otherTopics" },
    {
      label: "ผลการติดตาม/นิเทศ - ประเด็นอื่นๆ",
      value: "supervisionResult_section7",
    },
    { label: "ควรเป็นแหล่งฝึกต่อไป", value: "overall.shouldContinue" },
    { label: "ควรพัฒนาแหล่งฝึก", value: "overall.shouldImprove" },
    { label: "ไม่ควรใช้แหล่งฝึก", value: "overall.shouldNotUse" },
    { label: "แผนการพัฒนาในอนาคต", value: "overall.futurePlan" },
  ],
  3: [
    { label: "ชื่อแหล่งฝึก", value: "siteName" },
    { label: "สาขา", value: "branch" },
    { label: "ที่อยู่", value: "address" },
    { label: "ตำบล/แขวง", value: "district" },
    { label: "อำเภอ/เขต", value: "amphoe" },
    { label: "จังหวัด", value: "province" },
    { label: "รหัสไปรษณีย์", value: "postcode" },
    { label: "โทรศัพท์", value: "phone" },
    { label: "E-mail", value: "email" },
    { label: "ผู้รับชี้แจงการฝึกปฏิบัติงาน", value: "advisorName" },
    { label: "ร้านยาคุณภาพ - เป็นร้านยาคุณภาพ", value: "quality.isQuality" },
    { label: "ร้านยาคุณภาพ - จะเป็นร้านยาคุณภาพ", value: "quality.beQuality" },
    {
      label: "ร้านยาคุณภาพ - อยู่ระหว่างดำเนินการ",
      value: "quality.inProgress",
    },
    { label: "ร้านยาคุณภาพ - ร้านยาทั่วไป", value: "quality.general" },
    { label: "จำนวนผู้รับบริการต่อวัน", value: "servePerDay" },
    { label: "อาจารย์นิเทศ คนที่ 1", value: "advisors.0" },
    { label: "อาจารย์นิเทศ คนที่ 2", value: "advisors.1" },
    { label: "อาจารย์นิเทศ คนที่ 3", value: "advisors.2" },
    { label: "จำนวนนักศึกษารวม", value: "uniCounts.total" },
    { label: "จำนวนนักศึกษาชาย", value: "uniCounts.male" },
    { label: "จำนวนนักศึกษาหญิง", value: "uniCounts.female" },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - จุฬา",
      value: "universities.จุฬา",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - มหิดล",
      value: "universities.มหิดล",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - เชียงใหม่",
      value: "universities.เชียงใหม่",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - สงขลา",
      value: "universities.สงขลา",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - ศิลปากร",
      value: "universities.ศิลปากร",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - นเรศวร",
      value: "universities.นเรศวร",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - ขอนแก่น",
      value: "universities.ขอนแก่น",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - อุบลราชธานี",
      value: "universities.อุบลราชธานี",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - ศรีนครินทรวิโรฒ",
      value: "universities.ศรีนครินทรวิโรฒ",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - มหาสารคาม",
      value: "universities.มหาสารคาม",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - รังสิต",
      value: "universities.รังสิต",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - หัวเฉียวฯ",
      value: "universities.หัวเฉียวฯ",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - สยาม",
      value: "universities.สยาม",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - พายัพ",
      value: "universities.พายัพ",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - วลัยลักษณ์",
      value: "universities.วลัยลักษณ์",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - พะเยา",
      value: "universities.พะเยา",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - อีสเทิร์น",
      value: "universities.อีสเทิร์น",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - บูรพา",
      value: "universities.บูรพา",
    },
    {
      label: "มหาวิทยาลัยที่ส่งนักศึกษามาฝึก - ธรรมศาสตร์",
      value: "universities.ธรรมศาสตร์",
    },
    { label: "มหาวิทยาลัยอื่นๆ (ระบุ)", value: "universitiesOther" },
    { label: "ผลัดที่ 1 - จำนวนนักศึกษา", value: "shifts.0.count" },
    { label: "ผลัดที่ 2 - จำนวนนักศึกษา", value: "shifts.1.count" },
    { label: "ผลัดที่ 3 - จำนวนนักศึกษา", value: "shifts.2.count" },
    { label: "ผลัดที่ 4 - จำนวนนักศึกษา", value: "shifts.3.count" },
    { label: "ผลัดที่ 5 - จำนวนนักศึกษา", value: "shifts.4.count" },
    { label: "ผลัดที่ 6 - จำนวนนักศึกษา", value: "shifts.5.count" },
    { label: "ผลัดที่ 7 - จำนวนนักศึกษา", value: "shifts.6.count" },
    { label: "ผลัดที่ 8 - จำนวนนักศึกษา", value: "shifts.7.count" },
    { label: "ที่พัก - ที่พักโรงพยาบาล", value: "housing.hospDorm" },
    { label: "ที่พัก - ที่พักเอกชน", value: "housing.privateDorm" },
    { label: "ที่พัก - จัดหาเอง", value: "housing.self" },
    { label: "ความปลอดภัยที่พักและการเดินทาง", value: "safetyStayTravel" },
    { label: "หมายเหตุความปลอดภัยที่พัก", value: "safetyStayTravelNote" },
    { label: "ความปลอดภัยสิ่งแวดล้อม", value: "safetyEnv" },
    { label: "หมายเหตุความปลอดภัยสิ่งแวดล้อม", value: "safetyEnvNote" },
    { label: "การซักประวัติการใช้ยา", value: "activitiesDone.history" },
    { label: "การวัดสัญญาณชีพ", value: "activitiesDone.vitalSigns" },
    { label: "การให้คำแนะนำป้องกันโรค", value: "activitiesDone.diseasePrev" },
    {
      label: "การสอบถามประวัติการใช้ยา",
      value: "activitiesDone.medUseHistory",
    },
    {
      label: "การส่งต่อผู้ป่วยที่สงสัยมีปัญหาการใช้ยา",
      value: "activitiesDone.referSuspect",
    },
    {
      label: "การให้คำปรึกษาผู้ป่วยโรคเรื้อรัง",
      value: "activitiesDone.counselingChronic",
    },
    { label: "การคัดแยกผู้ป่วย (Triage)", value: "activitiesDone.triage" },
    {
      label: "การส่งต่อไปยังหน่วยบริการที่เหมาะสม",
      value: "activitiesDone.referToService",
    },
    {
      label: "การทำ Medication Profile",
      value: "activitiesDone.medicationProfile",
    },
    { label: "การรายงาน ADR", value: "activitiesDone.ADR" },
    { label: "การอธิบายวิธีการใช้ยา", value: "activitiesDone.usageExplain" },
    { label: "การติดตามการใช้ยา", value: "activitiesDone.adherenceFollow" },
    { label: "การให้ความรู้ด้านสุขภาพ", value: "activitiesDone.healthEdu" },
    { label: "กิจกรรมชุมชน", value: "activitiesDone.community" },
    { label: "กิจกรรมอื่นๆ", value: "activitiesDone.other" },
    { label: "ความเห็นโดยรวมกิจกรรม", value: "activitiesDone.overallComment" },
    { label: "ปัญหา - การแต่งกาย", value: "p611.dress.note" },
    { label: "ปัญหา - เล็บและผม", value: "p611.nailHair.note" },
    { label: "ปัญหา - บุคลิกภาพ", value: "p611.personality.note" },
    { label: "ปัญหา - การตรงต่อเวลา", value: "p611.time.note" },
    { label: "ปัญหา - การยอมรับคำสั่ง", value: "p611.acceptOrder.note" },
    { label: "ปัญหา - การปฏิบัติตามกฎระเบียบ", value: "p611.obeyRules.note" },
    { label: "ปัญหา - การสื่อสารภาษาไทย", value: "p622.thaiComm.note" },
    { label: "ปัญหา - การสื่อสารทางการแพทย์", value: "p622.medicalComm.note" },
    { label: "ปัญหา - การสื่อสารภาษาอังกฤษ", value: "p622.englishComm.note" },
    { label: "ปัญหา - มารยาทในการให้บริการ", value: "p622.serviceManner.note" },
    { label: "ปัญหาอื่นๆ", value: "p623_other" },
    {
      label: "งานเภสัชกรรมคลินิก - การให้คำปรึกษา",
      value: "clinic.counseling.enable",
    },
    {
      label: "การให้คำปรึกษา - มี Profile",
      value: "clinic.counseling.hasProfile",
    },
    {
      label: "การให้คำปรึกษา - มีการส่งต่อ",
      value: "clinic.counseling.hasReferral",
    },
    {
      label: "การให้คำปรึกษา - มีการติดตาม",
      value: "clinic.counseling.hasFollowup",
    },
    {
      label: "การให้คำปรึกษา - จำนวนต่อวัน",
      value: "clinic.counseling.byStuPerDay",
    },
    {
      label: "การให้คำปรึกษา - แหล่งข้อมูล",
      value: "clinic.counseling.infoFrom",
    },
    {
      label: "งานเภสัชกรรมคลินิก - การช่วยเลิกบุหรี่",
      value: "clinic.stopSmoking.enable",
    },
    { label: "การช่วยเลิกบุหรี่ - ระดับ", value: "clinic.stopSmoking.level" },
    {
      label: "การช่วยเลิกบุหรี่ - มี Guideline",
      value: "clinic.stopSmoking.hasGuideline",
    },
    {
      label: "การช่วยเลิกบุหรี่ - แผนในปี",
      value: "clinic.stopSmoking.plannedYear",
    },
    {
      label: "การช่วยเลิกบุหรี่ - ผลิตภัณฑ์",
      value: "clinic.stopSmoking.products",
    },
    {
      label: "งานเภสัชกรรมคลินิก - การคัดกรองความเสี่ยง",
      value: "clinic.riskScreen.enable",
    },
    {
      label: "การคัดกรองความเสี่ยง - เบาหวาน",
      value: "clinic.riskScreen.targets.DM",
    },
    {
      label: "การคัดกรองความเสี่ยง - ความดันโลหิตสูง",
      value: "clinic.riskScreen.targets.HT",
    },
    {
      label: "การคัดกรองความเสี่ยง - อื่นๆ",
      value: "clinic.riskScreen.targets.other",
    },
    {
      label: "การคัดกรองความเสี่ยง - ช่วงเวลา",
      value: "clinic.riskScreen.timing",
    },
    {
      label: "การคัดกรองความเสี่ยง - โครงการคุณภาพ",
      value: "clinic.riskScreen.qualityProgram",
    },
    {
      label: "งานเภสัชกรรมคลินิก - การดูแลผู้ป่วยที่บ้าน",
      value: "clinic.homeCare.enable",
    },
    {
      label: "การดูแลผู้ป่วยที่บ้าน - ประเภทบริการ",
      value: "clinic.homeCare.isService",
    },
    {
      label: "การดูแลผู้ป่วยที่บ้าน - โครงการคุณภาพ",
      value: "clinic.homeCare.qualityProgram",
    },
    {
      label: "งานเภสัชกรรมคลินิก - การตรวจคัดกรองมวลชน",
      value: "clinic.massScreen.enable",
    },
    { label: "การตรวจคัดกรองมวลชน - แผนการ", value: "clinic.massScreen.plan" },
    {
      label: "การตรวจคัดกรองมวลชน - ดำเนินการโดย",
      value: "clinic.massScreen.by",
    },
    { label: "งานเภสัชกรรมคลินิกอื่นๆ", value: "clinic.other" },
    {
      label: "ความเห็นแหล่งฝึก - การประสานงาน",
      value: "hostComments.coordination.note",
    },
    {
      label: "ความเห็นแหล่งฝึก - คู่มือการฝึกงาน",
      value: "hostComments.printing.note",
    },
    {
      label: "ความเห็นแหล่งฝึก - การส่งนักศึกษา",
      value: "hostComments.sendStudents.note",
    },
    {
      label: "ความเห็นแหล่งฝึก - แบบประเมิน",
      value: "hostComments.assessmentForm.note",
    },
    { label: "ความเห็นแหล่งฝึก - อื่นๆ", value: "hostComments.other.note" },
    { label: "ต้องการสนับสนุน - หนังสือ", value: "support.book" },
    { label: "ต้องการสนับสนุน - การอบรมทางวิชาการ", value: "support.academic" },
    {
      label: "ต้องการสนับสนุน - Short course training",
      value: "support.shortCourse",
    },
    {
      label: "ต้องการสนับสนุน - ปรึกษางานวิจัย",
      value: "support.researchConsult",
    },
    { label: "ต้องการสนับสนุน - อื่นๆ", value: "support.other" },
    { label: "ยินยอมสำรวจข้อมูลออนไลน์", value: "consentSurvey" },
    { label: "เหตุผลยินยอม/ไม่ยินยอมสำรวจ", value: "consentSurveyReason" },
    { label: "ยินยอมส่งต่อข้อมูลผู้รับบริการ", value: "consentClientData" },
    {
      label: "เหตุผลยินยอม/ไม่ยินยอมส่งต่อข้อมูล",
      value: "consentClientDataReason",
    },
    { label: "การประเมิน - เหมาะสมทั่วไป", value: "siteEvaluation.suitable" },
    {
      label: "การประเมิน - เหมาะสมเฉพาะด้าน",
      value: "siteEvaluation.suitableSpecific",
    },
    {
      label: "การประเมิน - รายละเอียดเฉพาะด้าน",
      value: "siteEvaluation.suitableSpecificText",
    },
    { label: "การประเมิน - อื่นๆ", value: "siteEvaluation.other" },
    { label: "การประเมิน - หมายเหตุ", value: "siteEvaluation.note" },
  ],
  4: [
    { label: "ชื่อแหล่งฝึก", value: "siteName" },
    { label: "วันที่นิเทศ", value: "visitDate" },
    { label: "ครั้งที่", value: "visitRound" },
    { label: "ชื่อ-สกุลนักศึกษา คนที่ 1", value: "students.0" },
    { label: "ชื่อ-สกุลนักศึกษา คนที่ 2", value: "students.1" },
    { label: "ชื่อ-สกุลนักศึกษา คนที่ 3", value: "students.2" },
    { label: "ชื่อ-สกุลนักศึกษา คนที่ 4", value: "students.3" },
    { label: "สรุปผลจากการนิเทศ", value: "summary" },
    { label: "เคยรับนักศึกษาฝึกงาน", value: "siteInfo.everAccepted" },
    { label: "ไม่เคยรับนักศึกษาฝึกงาน", value: "siteInfo.neverAccepted" },
    {
      label: "มีนักศึกษาจากสถาบันอื่นร่วมฝึก",
      value: "siteInfo.hasOtherUniWithDorm",
    },
    {
      label: "ไม่มีนักศึกษาจากสถาบันอื่นร่วมฝึก",
      value: "siteInfo.hasOtherUniWithoutDorm",
    },
    {
      label: "ระบุสถาบันอื่น (จำนวน/ชั้นปี/สถาบัน)",
      value: "siteInfo.otherUniDesc",
    },
    {
      label: "ผลการติดตาม/นิเทศ - ข้อมูลแหล่งฝึก",
      value: "siteInfo.supervisionResult",
    },
    { label: "ที่พักที่ทำงานจัดให้", value: "housing.workplaceDorm" },
    { label: "บ้านพัก/บ้านญาติ", value: "housing.houseOrRelative" },
    { label: "ที่พักเอกชน", value: "housing.privateDorm" },
    { label: "ที่พักอื่นๆ", value: "housing.other" },
    { label: "รายละเอียดการเดินทาง/ความปลอดภัย", value: "housing.note" },
    { label: "ผลการติดตาม/นิเทศ - ที่พัก", value: "housing.supervisionResult" },
    {
      label: "แหล่งฝึกได้ให้รายชื่อการประสานงาน",
      value: "coordination.contactPersonProvided",
    },
    { label: "ต้องส่งเอกสารเพิ่มเติม", value: "coordination.needMoreDocs" },
    {
      label: "ติดต่อผ่านหมายเลขโทรศัพท์มือถือ",
      value: "coordination.viaMobile",
    },
    {
      label: "ติดต่อผ่านโทรศัพท์ภายใน/โครงการ",
      value: "coordination.viaLandlineOrProject",
    },
    {
      label: "ติดต่อผ่าน e-mail หรือ social network",
      value: "coordination.viaEmailOrSocial",
    },
    {
      label: "รายละเอียดช่องทางติดต่อ",
      value: "coordination.contactDetailJudge",
    },
    {
      label: "ข้อเสนอแนะช่องทางติดต่อ",
      value: "coordination.contactDetailNote",
    },
    {
      label: "ผลการติดตาม/นิเทศ - การประสานงาน",
      value: "coordination.supervisionResult",
    },
    {
      label: "ความพร้อมของเภสัชกรประจำแหล่งฝึก",
      value: "readiness.workloadFit",
    },
    { label: "หมายเหตุความพร้อมเภสัชกร", value: "readiness.workloadNote" },
    { label: "บุคลิกภาพและความประพฤติ", value: "readiness.studentPersonality" },
    {
      label: "ความรู้และการเตรียมตัวก่อนการฝึกงาน",
      value: "readiness.studentAcademic",
    },
    {
      label: "ความกระตือรือร้น ความรับผิดชอบและเอาใจใส่",
      value: "readiness.studentResponsibility",
    },
    { label: "ความพร้อมของนักศึกษา - อื่นๆ", value: "readiness.studentOther" },
    {
      label: "ผลการติดตาม/นิเทศ - ความพร้อม",
      value: "readiness.supervisionResult",
    },
    { label: "ต้องการสนับสนุน - หนังสือ/ตำรา", value: "supportNeeds.books" },
    {
      label: "ต้องการสนับสนุน - การประชุมวิชาการ",
      value: "supportNeeds.conferences",
    },
    {
      label: "ต้องการสนับสนุน - การอบรม/ดูงาน",
      value: "supportNeeds.trainingOrStudyVisit",
    },
    { label: "ต้องการสนับสนุน - อื่นๆ", value: "supportNeeds.other" },
    { label: "รายละเอียดการสนับสนุน", value: "supportNeeds.detail" },
    {
      label: "ผลการติดตาม/นิเทศ - การสนับสนุน",
      value: "supportNeeds.supervisionResult",
    },
    { label: "ไม่พบปัญหา/อุปสรรค", value: "obstacles.none" },
    { label: "พบปัญหา/อุปสรรค", value: "obstacles.has" },
    { label: "รายละเอียดปัญหา/แนวทางแก้ไข", value: "obstacles.note" },
    {
      label: "ผลการติดตาม/นิเทศ - ปัญหา/อุปสรรค",
      value: "obstacles.supervisionResult",
    },
    { label: "ประเด็นอื่นๆ", value: "otherTopics" },
    { label: "ควรเป็นแหล่งฝึกในปีต่อไป", value: "overall.shouldContinue" },
    {
      label: "เหตุผลควรเป็นแหล่งฝึกในปีต่อไป",
      value: "overall.shouldContinueText",
    },
    { label: "ควรมีการพัฒนาแหล่งฝึก", value: "overall.shouldImprove" },
    { label: "ข้อเสนอแนะการพัฒนาแหล่งฝึก", value: "overall.shouldImproveText" },
    { label: "ไม่ควรใช้แหล่งฝึก", value: "overall.shouldNotUse" },
    { label: "เหตุผลไม่ควรใช้แหล่งฝึก", value: "overall.shouldNotUseText" },
    {
      label: "การพัฒนา/ปรับปรุงแผนการนิเทศในอนาคต",
      value: "overall.futurePlan",
    },
  ],
  5: [
    { label: "E-mail", value: "email" },
    { label: "โทรศัพท์", value: "phone" },
    { label: "การติดต่อนิเทศงาน/สรุปการฝึกปฏิบัติงาน", value: "c_comm" },
    { label: "การแจ้งรายชื่อนิสิต/นักศึกษาฝึกงาน", value: "c_list" },
    { label: "ถนน", value: "street" },
    { label: "ที่อยู่เลขที่", value: "address" },
    {
      label: "การนัดหมายแหล่งฝึกและการชี้แจงรายละเอียดการฝึกปฏิบัติงานวิชาชีพ",
      value: "c_brief",
    },
    {
      label: "การประสานงานในกรณีที่เกิดปัญหาในระหว่างการฝึกปฏิบัติงาน",
      value: "c_issue",
    },
    { label: "ยา - ฝึกรวม", value: "product.1_1" },
    { label: "ยา - การผลิต", value: "product.1_2" },
    { label: "ยา - การควบคุมคุณภาพ/การประกันคุณภาพ", value: "product.1_3" },
    { label: "ยา - การวิจัยและพัฒนา", value: "product.1_4" },
    { label: "ยา - การขึ้นทะเบียน", value: "product.1_5" },
    { label: "ยา - การคุ้มครองผู้บริโภค", value: "product.1_6" },
    { label: "ยา - อื่นๆ (ระบุ)", value: "product.1_7" },
    { label: "ยา - ไม่มีการฝึกปฏิบัติ", value: "product.1_8" },
    { label: "ชีววัตถุ - ฝึกรวม", value: "product.2_1" },
    { label: "ชีววัตถุ - การผลิต", value: "product.2_2" },
    {
      label: "ชีววัตถุ - การควบคุมคุณภาพ/การประกันคุณภาพ",
      value: "product.2_3",
    },
    { label: "ชีววัตถุ - การวิจัยและพัฒนา", value: "product.2_4" },
    { label: "ชีววัตถุ - การขึ้นทะเบียน", value: "product.2_5" },
    { label: "ชีววัตถุ - การคุ้มครองผู้บริโภค", value: "product.2_6" },
    { label: "ชีววัตถุ - อื่นๆ (ระบุ)", value: "product.2_7" },
    { label: "ชีววัตถุ - ไม่มีการฝึกปฏิบัติ", value: "product.2_8" },
    { label: "เครื่องสำอาง - ฝึกรวม", value: "product.3_1" },
    { label: "เครื่องสำอาง - การผลิต", value: "product.3_2" },
    {
      label: "เครื่องสำอาง - การควบคุมคุณภาพ/การประกันคุณภาพ",
      value: "product.3_3",
    },
    { label: "เครื่องสำอาง - การวิจัยและพัฒนา", value: "product.3_4" },
    { label: "เครื่องสำอาง - การขึ้นทะเบียน", value: "product.3_5" },
    { label: "เครื่องสำอาง - การคุ้มครองผู้บริโภค", value: "product.3_6" },
    { label: "เครื่องสำอาง - อื่นๆ (ระบุ)", value: "product.3_7" },
    { label: "เครื่องสำอาง - ไม่มีการฝึกปฏิบัติ", value: "product.3_8" },
    { label: "สมุนไพร - ฝึกรวม", value: "product.4_1" },
    { label: "สมุนไพร - การผลิต", value: "product.4_2" },
    {
      label: "สมุนไพร - การควบคุมคุณภาพ/การประกันคุณภาพ",
      value: "product.4_3",
    },
    { label: "สมุนไพร - การวิจัยและพัฒนา", value: "product.4_4" },
    { label: "สมุนไพร - การขึ้นทะเบียน", value: "product.4_5" },
    { label: "สมุนไพร - การคุ้มครองผู้บริโภค", value: "product.4_6" },
    { label: "สมุนไพร - อื่นๆ (ระบุ)", value: "product.4_7" },
    { label: "สมุนไพร - ไม่มีการฝึกปฏิบัติ", value: "product.4_8" },
    { label: "อาหารและผลิตภัณฑ์เสริมอาหาร - ฝึกรวม", value: "product.5_1" },
    { label: "อาหารและผลิตภัณฑ์เสริมอาหาร - การผลิต", value: "product.5_2" },
    {
      label: "อาหารและผลิตภัณฑ์เสริมอาหาร - การควบคุมคุณภาพ/การประกันคุณภาพ",
      value: "product.5_3",
    },
    {
      label: "อาหารและผลิตภัณฑ์เสริมอาหาร - การวิจัยและพัฒนา",
      value: "product.5_4",
    },
    {
      label: "อาหารและผลิตภัณฑ์เสริมอาหาร - การขึ้นทะเบียน",
      value: "product.5_5",
    },
    {
      label: "อาหารและผลิตภัณฑ์เสริมอาหาร - การคุ้มครองผู้บริโภค",
      value: "product.5_6",
    },
    {
      label: "อาหารและผลิตภัณฑ์เสริมอาหาร - อื่นๆ (ระบุ)",
      value: "product.5_7",
    },
    {
      label: "อาหารและผลิตภัณฑ์เสริมอาหาร - ไม่มีการฝึกปฏิบัติ",
      value: "product.5_8",
    },
    {
      label: "ทักษะในการสื่อสารและการใช้เทคโนโลยีสารสนเทศ",
      value: "ratings.s312_it",
    },
    {
      label: "อาจารย์แหล่งฝึกใส่ใจดูแลการฝึกปฏิบัติงาน",
      value: "ratings.s21_care",
    },
    { label: "ความสามารถในการใช้ภาษาอังกฤษ", value: "ratings.s312_eng" },
    {
      label: "นิสิต/นักศึกษามีความพร้อมในการฝึกปฏิบัติงาน",
      value: "ratings.s21_ready",
    },
    {
      label: "ความสามารถในการประสานงานและทำงานเป็นทีม",
      value: "ratings.s312_team",
    },
    { label: "แต่งกายสุภาพ เรียบร้อย", value: "ratings.s311_dress" },
    {
      label: "ปฏิบัติตัวตามระเบียบข้อบังคับของแหล่งฝึก",
      value: "ratings.s311_rules",
    },
    {
      label: "ความหลากหลายของหน่วยงานที่เหมาะสมกับการฝึกปฏิบัติงาน",
      value: "ratings.s21_variety",
    },
    {
      label: "กิริยาพูดจาสุภาพ วางตัวเหมาะสม ถูกต้องตามกาลเทศะ",
      value: "ratings.s311_manner",
    },
    { label: "การเรียนรู้แบบ active learning", value: "ratings.s312_active" },
    {
      label: "ความนอบน้อมและมีสัมมาคารวะต่ออาจารย์แหล่งฝึก",
      value: "ratings.s311_respect",
    },
    {
      label: "การเตรียมตัวก่อนการฝึกปฏิบัติงาน",
      value: "ratings.s312_prepare",
    },
    { label: "ความตรงต่อเวลา", value: "ratings.s311_punctual" },
    {
      label: "ความคิดเชิงวิเคราะห์และสังเคราะห์",
      value: "ratings.s312_critical",
    },
    {
      label: "การวางแผนการฝึกปฏิบัติงานอย่างเป็นระบบ",
      value: "ratings.s21_systematic",
    },
    {
      label: "ความกระตือรือร้นในการฝึกปฏิบัติงาน",
      value: "ratings.s311_integrity",
    },
    { label: "ความรู้เพียงพอและเหมาะสม", value: "ratings.s312_knowledge" },
    {
      label: "ความรับผิดชอบต่องานที่ได้รับมอบหมาย",
      value: "ratings.s311_responsible",
    },
    {
      label: "จำนวนนิสิต/นักศึกษาที่ฝึกปฏิบัติงานในช่วงเดียวกัน",
      value: "ratings.s21_student_count",
    },
    {
      label: "จำนวนอาจารย์ที่ดูแลการฝึกปฏิบัติงาน",
      value: "ratings.s21_teacher_count",
    },
    {
      label: "จำนวนนิสิต/นักศึกษาเหมาะสมต่อการฝึกปฏิบัติงาน",
      value: "ratings.s21_student_appropriate",
    },
    {
      label: "จำนวนอาจารย์เหมาะสมต่อการฝึกปฏิบัติงาน",
      value: "ratings.s21_teacher_appropriate",
    },
    { label: "รถรับ/ส่ง", value: "shuttle" },
    { label: "การสำรวจการรับนิสิต/นักศึกษา", value: "c_survey" },
    {
      label: "การประสานงานทั่วไปเกี่ยวกับการเดินทางของนิสิต/นักศึกษาและที่พัก",
      value: "c_travel",
    },
    { label: "อำเภอ/เขต", value: "district" },
    { label: "จังหวัด", value: "province" },
    {
      label: "หัวข้อและรูปแบบการประเมินผลตามคู่มือเหมาะสมหรือไม่",
      value: "s324_fit",
    },
    { label: "กิจกรรมที่ทำได้เทียบกับคู่มือการฝึก", value: "s322_mode" },
    {
      label: "การยืนยันการฝึกงานของนิสิต/นักศึกษาของแต่ละมหาวิทยาลัย",
      value: "c_register",
    },
    {
      label: "การลงนามในสัญญาห้ามเปิดเผยข้อมูล (Confidentiality Agreement)",
      value: "conf_agree",
    },
    { label: "เภสัชกรผู้รับผิดชอบการฝึกปฏิบัติงาน", value: "pharmacist" },
    { label: "ตำบล/แขวง", value: "subdistrict" },
    { label: "ข้อเสนอแนะเพิ่มเติม", value: "comment_esp" },
    { label: "ข้อเสนอแนะจากนิสิต/นักศึกษา", value: "comment_stud" },
    { label: "ความปลอดภัย", value: "safety_level" },
    { label: "ที่พัก", value: "accommodation" },
    { label: "ค่าเบี้ยเลี้ยงจากแหล่งฝึก", value: "allowance_has" },
    { label: "ระยะเวลาการฝึกที่เหมาะสม", value: "s323_duration" },
    { label: "การนำเสนอการฝึกงาน", value: "teacher_visit" },
    { label: "ค่าที่พัก", value: "housing_fee_has" },
    { label: "การเดินทาง", value: "commute_easy" },
    { label: "ผลัดที่", value: "stu_round" },
    { label: "มหาวิทยาลัย", value: "stu_uni" },
    { label: "รวมจำนวนนิสิต/นักศึกษา (คน)", value: "stu_total" },
    {
      label: "จำนวนนิสิต/นักศึกษาที่ฝึกปฏิบัติงานในช่วงเดียวกัน",
      value: "student_count",
    },
    { label: "จำนวนอาจารย์ที่ดูแลการฝึกปฏิบัติงาน", value: "teacher_count" },
    { label: "กิจกรรมฝึกที่หน่วยงานให้กับนักศึกษา (สรุป)", value: "s321_text" },
    { label: "ข้อเสนอแนะการฝึกตามคู่มือ", value: "s322_note" },
    { label: "ช่วงเวลาที่เหมาะสม", value: "s323_when" },
    { label: "ข้อเสนอแนะระยะเวลาการฝึก", value: "s323_note" },
    { label: "ข้อเสนอแนะการประเมินผล", value: "s324_note" },
    { label: "ข้อเสนอแนะอื่นๆ", value: "c_other" },
    { label: "จำนวนเงินค่าที่พัก", value: "housing_fee_amt" },
    { label: "จำนวนเงินค่าเบี้ยเลี้ยง", value: "allowance_amt" },
    { label: "หน่วยเงินค่าเบี้ยเลี้ยง", value: "allowance_per" },
  ],
};
